name: Build with PyInstaller

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Build with PyInstaller
      run: python src/remoteplay-runner.py --create-executable

    - name: Set version
      id: version
      run: echo "::set-output name=version::$(python src/remoteplay-runner.py --version)"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{steps.version.outputs.version}}
        draft: false
        prerelease: false
        body_path: CHANGELOG.md

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/remoteplay.exe
        asset_name: remoteplay.exe
        asset_content_type: application/octet-stream