name: Build with PyInstaller

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Build with PyInstaller
      run: python src/remoteplay-runner.py --create-executable
